### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by domisol** [jandebleser/spideroak#1]
Hello
Running in Synology NAS
Command "SpiderOakONE --setup=/config.json" gives the following messages 
Logging in...                                                                   
Traceback (most recent call last):                                              
Failure: OpenSSL.SSL.Error: [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'ce
rtificate verify failed')]                                                      
Failure running setup: twisted.python.failure.Failure [('SSL routines', 'SSL3_GE
T_SERVER_CERTIFICATE', 'certificate verify failed')]    

https://support.spideroak.com/hc/en-us/articles/115005874603-SSL-Certificate-Verification-Error
"When you see an SSL certificate verification error while attempting to use a SpiderOak product, the most common reason is that you have an old version with an expired certificate".
I don't understand because Dockerfile contains 'RUN wget https://spideroak.com/release/spideroak/deb_x64' which is supposed to get the last release...
any solution ?
thanks
Jean-David

**Comment by domisol** [comment]
root@jandebleser-spideroak1:/# SpiderOakONE --version                      
SpiderOakONE v6.3.1.10180   
This is strange because current version is 7.2

**Comment by jandebleser** [comment]
The docker image was out of date. I've pushed a new version. The current version of the client is now 7.3.0
